dist: trusty


env:
  global:
    - RUN_SONAR_SCANNER=0
    - BACKWARD_COMPATIBILITY_FROM=v1.1.0

language: php


services:
    - docker


addons:
  chrome: stable
  sonarcloud:
    organization: "medicalmundi"
    token: $SECRET_SONAR_TOKEN


cache:
  directories:
  - $HOME/.composer/cache


.steps:
  #
  #   CI STEP
  #
  - &add-composer-bin-dir-to-path |
      export PATH="$PATH:$HOME/.composer/vendor/bin"

  - &disable-xdebug-php-extension |
      phpenv config-rm xdebug.ini || echo "xdebug not available"

  - &disable-php-memory-limit |
      echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  - &install-project-dependencies |
      composer install --no-progress --no-suggest --ansi

  - &lint-composer |
      composer validate --strict --no-check-lock --ansi -vvv

  - &run-phpunit-tests-with-coverage |
      ./vendor/bin/phpunit --colors=always --coverage-clover=coverage-report.clover --log-junit=test-report.xml

  - &run-phpunit-tests |
      ./vendor/bin/phpunit --colors=always

  - &run-code-style-check |
      ./vendor/bin/php-cs-fixer fix --dry-run -v

  - &run-static-analysis-check |
      ./vendor/bin/phpstan analyse


jobs:
  include:
    - name: '(PHP 7.2)'
      php: '7.2'
      env: RUN_SONAR_SCANNER=1
      before_install:
        - *disable-php-memory-limit
      install:
        - *install-project-dependencies
      before_script:
        - *lint-composer
      script:
        - *run-code-style-check
        - *run-static-analysis-check
        - *run-phpunit-tests-with-coverage
      after_success:
        - if [[ $RUN_SONAR_SCANNER == "1" ]]; then sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.projectVersion=$TRAVIS_BRANCH; fi


    - name: '(PHP 7.3)'
      php: '7.3'
      before_install:
        - *disable-xdebug-php-extension
        - *disable-php-memory-limit
      install:
        - *install-project-dependencies
      before_script:
        - *lint-composer
      script:
        - *run-phpunit-tests


    - name: '(PHP 7.4)'
      php: '7.4'
      before_install:
        - *disable-xdebug-php-extension
        - *disable-php-memory-limit
      install:
        - *install-project-dependencies
      before_script:
        - *lint-composer
      script:
        - *run-phpunit-tests


    - name: 'Roave Backward Compatibility Check'
      php: '7.2'
      env: RUN_SONAR_SCANNER=0
      before_install:
        - *disable-xdebug-php-extension
        - *disable-php-memory-limit
      install:
        - *install-project-dependencies
      script:
        - vendor/bin/roave-backward-compatibility-check --from=$BACKWARD_COMPATIBILITY_FROM


  allow_failures:
    - name: 'Roave Backward Compatibility Check'